---
title: "04 Data Visualization"
date: "2021-04"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    collapsed: false
    number_sections: true
    toc_depth: 3
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```
# Challenge 

Goal: Map the time course of the cumulative Covid-19 cases with country 

```{r}
# Import dependencies 

library(tidyverse)
library(lubridate)
library(ggthemes)
library(ggrepel)
library(purrr)
library(maps)


#load data and preprocess 
covid_data_tbl <- read_csv("https://covid.ourworldindata.org/data/owid-covid-data.csv") %>%
  select(location, date, total_cases) %>%
  filter(location == "Germany" | location == "United Kingdom" | location == "France" | location == "Spain" | location == "United States")%>%
  mutate(cases_dec = scales::dollar(total_cases, big.mark = ".", 
                                    decimal.mark = ",", 
                                    prefix = "", 
                                    suffix = ""))


#challenge 1 : plotting data

covid_data_tbl %>%
ggplot(aes(x = date, y = total_cases, color = location)) +


geom_line(size = 1) +

geom_label_repel(aes(x=date, y=total_cases, label=cases_dec) , 
                 data = covid_data_tbl %>% slice(which.max(total_cases)),
                 vjust = 0.5, 
                 hjust = 0.5,color = "green")+

expand_limits(y = 0) +

scale_y_continuous(labels = scales::dollar_format(scale = 1/1e6,
                                                  prefix = "",
                                                  suffix = "M")) +

scale_x_date(date_labels = "%B %Y", 
             date_breaks = "1 month", 
             expand = c(0,NA)) +
# # labeling the plot
  
labs(
  title = "Confirmed cases Covid-19 around the world",
  subtitle = "As of 07/05/2021",
  x = "Months",
  y = "Cumulative Cases",
  color = "Country or Location"
  )  +
  
  theme_light() +
  theme(title = element_text(face = "bold", color = "Black"),
        legend.position  = "bottom",
        axis.text.x = element_text(angle = 45))

```

Goal: Visualize the distribution of the mortality rate (deaths / population) with geom_map(). The necessary longitudinal and lateral data can be accessed with this function:

```{r}
# import dependencies 

library(tidyverse)
library(lubridate)
library(ggthemes)
library(ggrepel)
library(purrr)
library(maps)


# load data and preprocess 

covid_data_tbl <- read_csv("https://covid.ourworldindata.org/data/owid-covid-data.csv")%>%
mutate(mort_rate = total_deaths/population)%>%
group_by(location) %>% summarise(Mortality_Rate = last(mort_rate))%>%
select(location, Mortality_Rate)%>%
mutate(location = case_when(

#  join the lat/long data and the covid data   
  
location == "United Kingdom" ~ "UK",
location == "United States" ~ "USA",
location == "Democratic Republic of Congo" ~ "Democratic Republic of the Congo",
TRUE ~ location
    
  )) %>%
distinct()
world <- map_data("world")
covid_coord <- merge(x=world,y=covid_data_tbl, by.x = "region", by.y = "location")%>%
select(region, long,lat,Mortality_Rate)

# creating world map plot using geom map

covid_coord %>% ggplot() + 
geom_map(aes(x = long, y = lat, map_id = region, fill = Mortality_Rate), map = world) +

# labeling the plot
  
scale_fill_continuous(labels = scales::percent_format(accuracy = 0.001), low = "navyblue", high = "turquoise1") +
labs(
  title = "Confirmed COVID-19 deaths relative to the size of the population",
  subtitle = "More than 3 Million confirmed Covid-19 deaths worldwide",
  caption = "Date: 05/07/2021") +


theme(axis.line = element_blank(), axis.text = element_blank(), axis.ticks = element_blank(), axis.title = element_blank()) +

theme(title = element_text(face = "bold", color = "gray15"),
      legend.position  = "right")



```
